// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywuohaerrgiddojxsgqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3dW9oYWVycmdpZGRvanhzZ3FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTY3NDQsImV4cCI6MjA2MTQzMjc0NH0.L-8uHryQPMyk5gcaRP0MoC25XFao37ehpyRuDToVQJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);